insert into intermedio(id, enunciado, codigo, respuesta) values (1, "¿Qué imprime el código?", "list1 = [1, 2, 3, 4]\nprint(sum(list1))", "10");
insert into intermedio(id, enunciado, codigo, respuesta) values (2, "¿Qué valor tiene el último elemento?", "list2 = [5,6,7,8]\nprint(list2[-1])", "8");
insert into intermedio(id, enunciado, codigo, respuesta) values (3, "¿Qué se muestra?", "str3 = 'hello world'\nprint(str3[::-1])", "dlrow olleh");
insert into intermedio(id, enunciado, codigo, respuesta) values (4, "¿Cuántos elementos tiene la lista?", "list3 = [1, 2, 3, 4, 5]\nprint(len(list3))", "5");
insert into intermedio(id, enunciado, codigo, respuesta) values (5, "¿Qué se imprime?", "x = 5\nprint(x == 5)", "True");
insert into intermedio(id, enunciado, codigo, respuesta) values (6, "¿Qué valor se imprime?", "y = 5\nz = 2\nprint(y * z)", "10");
insert into intermedio(id, enunciado, codigo, respuesta) values (7, "¿Qué imprime el código?", "str4 = 'python'\nprint(str4[1:4])", "yth");
insert into intermedio(id, enunciado, codigo, respuesta) values (8, "¿Qué se muestra?", "a = 5\nb = 6\nprint(a > b)", "False");
insert into intermedio(id, enunciado, codigo, respuesta) values (9, "¿Qué valor tiene c?", "c = 10\nprint(c != 10)", "False");
insert into intermedio(id, enunciado, codigo, respuesta) values (10, "¿Qué se imprime?", "d = [1,2,3]\ne = [1,2,3]\nprint(d == e)", "True");
insert into intermedio(id, enunciado, codigo, respuesta) values (11, "¿Cuál es el resultado?", "f = 'Python'.lower()\nprint(f)", "python");
insert into intermedio(id, enunciado, codigo, respuesta) values (12, "¿Qué se muestra por pantalla?", "g = 4.5\nprint(int(g))", "4");
insert into intermedio(id, enunciado, codigo, respuesta) values (13, "¿Qué imprime el código?", "h = 4\ni = 0\nprint(h / i)", "ZeroDivisionError");
insert into intermedio(id, enunciado, codigo, respuesta) values (14, "¿Cuál es el valor?", "j = '123'\nprint(int(j))", "123");
insert into intermedio(id, enunciado, codigo, respuesta) values (15, "¿Qué se imprime?", "k = '5.7'\nprint(float(k))", "5.7");
