insert into facil(id, enunciado, codigo, respuesta) values (1, "¿Qué imprime el siguiente código?", "x = 5\ny = 10\nprint(x + y)", "15");
insert into facil(id, enunciado, codigo, respuesta) values (2, "¿Qué valor tiene z?", "z = 3 * 4\nprint(z)", "12");
insert into facil(id, enunciado, codigo, respuesta) values (3, "¿Qué imprime el código?", "a = 2\nb = 3\nprint(a**b)", "8");
insert into facil(id, enunciado, codigo, respuesta) values (4, "¿Qué se muestra por pantalla?", "str1 = 'Hola'\nstr2 = ' Mundo!'\nprint(str1 + str2)", "Hola Mundo!");
insert into facil(id, enunciado, codigo, respuesta) values (5, "¿Cuál es el resultado?", "r = 6 // 2\nprint(r)", "3");
insert into facil(id, enunciado, codigo, respuesta) values (6, "¿Qué imprime este código?", "s = 'python'.upper()\nprint(s)", "PYTHON");
insert into facil(id, enunciado, codigo, respuesta) values (7, "¿Cuál es el valor de p?", "p = 7 % 5\nprint(p)", "2");
insert into facil(id, enunciado, codigo, respuesta) values (8, "¿Qué se muestra?", "t = 10\nu = 20\nprint(t * u)", "200");
insert into facil(id, enunciado, codigo, respuesta) values (9, "¿Cuál es el resultado?", "m = 24 // 4\nprint(m)", "6");
insert into facil(id, enunciado, codigo, respuesta) values (10, "¿Qué se imprime?", "c = 'PYTHON'[1]\nprint(c)", "Y");
insert into facil(id, enunciado, codigo, respuesta) values (11, "¿Qué valor tiene j?", "j = 8 + 7\nprint(j)", "15");
insert into facil(id, enunciado, codigo, respuesta) values (12, "¿Qué imprime el código?", "k = 6 * 3\nprint(k)", "18");
insert into facil(id, enunciado, codigo, respuesta) values (13, "¿Cuál es el valor de l?", "l = 12 % 5\nprint(l)", "2");
insert into facil(id, enunciado, codigo, respuesta) values (14, "¿Qué se muestra por pantalla?", "q = 9 - 6\nprint(q)", "3");
insert into facil(id, enunciado, codigo, respuesta) values (15, "¿Cuál es el resultado?", "w = 3**2\nprint(w)", "9");
